# Generated by Django 4.1.2 on 2022-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.IntegerField()),
                ('username', models.CharField(max_length=40)),
            ],
        ),
    ]
