# Generated by Django 4.1.2 on 2022-10-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newreminder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('date', models.IntegerField()),
                ('time', models.IntegerField()),
                ('repeat', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=60)),
            ],
        ),
    ]
