# Generated by Django 4.1.2 on 2022-10-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_pass', models.IntegerField(max_length=30)),
                ('user_email', models.IntegerField(max_length=20)),
            ],
        ),
    ]
