# Generated by Django 4.1.2 on 2022-10-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0002_alter_user_user_email_alter_user_user_pass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
